<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Conform\Conform.csproj" />
    <ProjectReference Include="..\..\src\Conform.Annotations\Conform.Annotations.csproj" />
  </ItemGroup>
</Project>
